travis:
  secure:
    BINSTAR_TOKEN: Dw0SxF9LCnh8faRImcNwV/toVgrM+iiNto+h2iZ4kII8Zotwgy4BDL8FxfMXi1J0Irz9O8x8HvP2Me2U1aeRJqWBYc2iy7cuNgSHwc1tn3wUG8hFLnn41gJIzEig2Tao9jFJGzYU6xAJiTdxz7bK9jcoY/1rPv//FJDIq0zmvB1F9W9BKemiwwr9Sg8WHQ8nTrp59o7ZHuxLYrcT2l1AIAUtfKGx7lxdo+8rTtvHjl6YRLwX2i+sgGY1Lo4MR58op8qtDnmRgjBa3XUl2JM2YXzlu4dLOoyqQ9kXYmuXzwqflCubYTITT1KCAfsS/q7EtMyVmJlDQ1mYwNIDMKpBMBCNYvrwUBr7EdFhJZFRgdWViDY5KkMlUxeHVCpBqh99JH1+SHar+cTfFLLS7grd9FwDHPSnBH5ctKR2Al68H11BUZ5UlV0QoZU7yLnI7O/yUve9edm0bIi2rsW/UMmiY8QKijg4Alr3KaR/+BCDsy0LoU7NltaXFM82Aj+QAF6h9u/Q+70egDByevRUOSGEN9EQn80+02uQTKyKoYNtp4HONg17UbgYkXuuJj+n1BSst8jL3PkVvHb53wJhANdfcUrZzgLeXbZ0CiAIyH8DmiBCQnnMcYDRY4oItXcRvTWAayYLyRE+SYw4L2dOcd07FtBawpEhQnS3t7BvFqR6p2c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
